import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const yearArgs = process.argv.slice(2)
  .map((value) => Number.parseInt(value, 10))
  .filter((value) => Number.isFinite(value) && value >= 2000);
const now = new Date();
const years = yearArgs.length > 0 ? yearArgs : [now.getUTCFullYear(), now.getUTCFullYear() + 1];

const holidayIdByName = new Map([
  ["元旦", "HolidayId::YuanDan"],
  ["春节", "HolidayId::ChunJie"],
  ["清明节", "HolidayId::QingMing"],
  ["劳动节", "HolidayId::LaoDong"],
  ["端午节", "HolidayId::DuanWu"],
  ["中秋节", "HolidayId::ZhongQiu"],
  ["国庆节", "HolidayId::GuoQing"],
]);

const outPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../include/logic/HolidayData.h",
);

async function fetchYear(year) {
  const url = `https://raw.githubusercontent.com/NateScarlet/holiday-cn/master/${year}.json`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }
  return response.json();
}

function pickHolidayStarts(dataset) {
  const starts = new Map();
  for (const day of dataset.days ?? []) {
    if (!day?.isOffDay) {
      continue;
    }
    const id = holidayIdByName.get(day.name);
    if (!id || starts.has(day.name)) {
      continue;
    }
    starts.set(day.name, {
      id,
      name: day.name,
      date: day.date,
    });
  }
  return [...starts.values()];
}

const datasets = await Promise.all(years.map(fetchYear));
const papers = [];
const entries = [];
for (const dataset of datasets) {
  for (const paper of dataset.papers ?? []) {
    if (!papers.includes(paper)) {
      papers.push(paper);
    }
  }
  for (const holiday of pickHolidayStarts(dataset)) {
    entries.push(holiday);
  }
}

entries.sort((left, right) => left.date.localeCompare(right.date));
const maxKnownYear = years.reduce((max, value) => Math.max(max, value), 0);
const nextNewYearDate = `${maxKnownYear + 1}-01-01`;
if (!entries.some((entry) => entry.date === nextNewYearDate)) {
  entries.push({
    id: "HolidayId::YuanDan",
    name: "元旦",
    date: nextNewYearDate,
  });
}
entries.sort((left, right) => left.date.localeCompare(right.date));

const body = `#pragma once

// Generated by tools/update_holiday_data.mjs from holiday-cn.
// Source papers:
${papers.map((paper) => `// - ${paper}`).join("\n") || "// - (none announced yet)"}

static const HolidayEntry kHolidayEntries[] = {
${entries.map((entry) => {
  const [year, month, day] = entry.date.split("-").map((value) => Number.parseInt(value, 10));
  return `    HolidayEntry(${entry.id}, ${year}, ${month}, ${day}),  // ${entry.name} ${entry.date}`;
}).join("\n")}
};
`;

writeFileSync(outPath, body);
console.log(`Wrote ${entries.length} holiday entries to ${outPath}`);
