import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const yearArgs = process.argv.slice(2)
  .map((value) => Number.parseInt(value, 10))
  .filter((value) => Number.isFinite(value) && value >= 2000);
const now = new Date();
const years = yearArgs.length > 0 ? yearArgs : [now.getUTCFullYear(), now.getUTCFullYear() + 1];

const holidayIdByName = new Map([
  ["元旦", "HolidayId::YuanDan"],
  ["春节", "HolidayId::ChunJie"],
  ["清明节", "HolidayId::QingMing"],
  ["劳动节", "HolidayId::LaoDong"],
  ["端午节", "HolidayId::DuanWu"],
  ["中秋节", "HolidayId::ZhongQiu"],
  ["国庆节", "HolidayId::GuoQing"],
]);

const outPath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../include/logic/HolidayData.h",
);

async function fetchYear(year) {
  const url = `https://raw.githubusercontent.com/NateScarlet/holiday-cn/master/${year}.json`;
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }
  return response.json();
}

function nextIsoDate(isoDate) {
  const [year, month, day] = isoDate.split("-").map((value) => Number.parseInt(value, 10));
  const value = new Date(Date.UTC(year, month - 1, day));
  value.setUTCDate(value.getUTCDate() + 1);
  return value.toISOString().slice(0, 10);
}

function pickHolidayPeriods(dataset) {
  const periods = [];
  let active = null;

  for (const day of dataset.days ?? []) {
    const id = holidayIdByName.get(day?.name);
    const isHolidayOffDay = Boolean(id && day?.isOffDay);
    if (!isHolidayOffDay) {
      if (active) {
        periods.push(active);
        active = null;
      }
      continue;
    }

    if (active &&
        active.name === day.name &&
        nextIsoDate(active.end) === day.date) {
      active.end = day.date;
      active.total_days += 1;
      continue;
    }

    if (active) {
      periods.push(active);
    }
    active = {
      id,
      name: day.name,
      start: day.date,
      end: day.date,
      total_days: 1,
    };
  }

  if (active) {
    periods.push(active);
  }
  return periods;
}

const datasets = await Promise.all(years.map(fetchYear));
const papers = [];
const periods = [];
for (const dataset of datasets) {
  for (const paper of dataset.papers ?? []) {
    if (!papers.includes(paper)) {
      papers.push(paper);
    }
  }
  for (const holidayPeriod of pickHolidayPeriods(dataset)) {
    periods.push(holidayPeriod);
  }
}

periods.sort((left, right) => left.start.localeCompare(right.start));
const maxKnownYear = years.reduce((max, value) => Math.max(max, value), 0);
const nextNewYearDate = `${maxKnownYear + 1}-01-01`;
if (!periods.some((period) => period.start === nextNewYearDate)) {
  periods.push({
    id: "HolidayId::YuanDan",
    name: "元旦",
    start: nextNewYearDate,
    end: nextNewYearDate,
    total_days: 1,
  });
}
periods.sort((left, right) => left.start.localeCompare(right.start));
const entries = periods.map((period) => ({
  id: period.id,
  name: period.name,
  date: period.start,
}));

const body = `#pragma once

// Generated by tools/update_holiday_data.mjs from holiday-cn.
// Source papers:
${papers.map((paper) => `// - ${paper}`).join("\n") || "// - (none announced yet)"}

static const HolidayEntry kHolidayEntries[] = {
${entries.map((entry) => {
  const [year, month, day] = entry.date.split("-").map((value) => Number.parseInt(value, 10));
  return `    HolidayEntry(${entry.id}, ${year}, ${month}, ${day}),  // ${entry.name} ${entry.date}`;
}).join("\n")}
};

static const HolidayPeriod kHolidayPeriods[] = {
${periods.map((period) => {
  const [startYear, startMonth, startDay] = period.start.split("-").map((value) => Number.parseInt(value, 10));
  const [endYear, endMonth, endDay] = period.end.split("-").map((value) => Number.parseInt(value, 10));
  return `    HolidayPeriod(${period.id}, ${startYear}, ${startMonth}, ${startDay}, ${endYear}, ${endMonth}, ${endDay}, ${period.total_days}),  // ${period.name} ${period.start}..${period.end}`;
}).join("\n")}
};
`;

writeFileSync(outPath, body);
console.log(`Wrote ${entries.length} holiday entries and ${periods.length} holiday periods to ${outPath}`);
